firebase/quickstart-android

messaging/README.md

This PR updates the link to the screenshot.

Fix the screenshot in the project description

---

admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
invites/app/build.gradle
messaging/app/build.gradle
storage/app/build.gradle

Change-Id: I477072a4bf91afebc1e5fad743b0c26cc311071f

Version bump to 9.0.2

---

app-indexing/app/build.gradle

Change-Id: I107c73eb741a686847eedb63bf854b92bae3b4e9

Fix App Indexing build

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java

Update to check for and handle both data and notification messages in onMessageReceived callback.

Handle both notification and data payloads

---

README.md
admob/README.md
analytics/README.md
app-indexing/README.md
auth/README.md
config/README.md
crash/README.md
database/README.md
dynamiclinks/README.md
invites/README.md
messaging/README.md

This is a pull request as part of Google Outreach Program with Professor Kelly from University of Waterloo.
Every single READMEs are updated (broken links, clarity, style, consistency, etc...)

dh-- University of Waterloo Updated README's

---

database/app/src/main/java/com/google/firebase/quickstart/database/NewPostActivity.java

Prevent double posting when WiFi off

---

storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MainActivity.java

Fix picture taking on Android KK and below

---

auth/build.gradle

Use the last version of gradle

last version of gradle

---

analytics/app/src/main/java/com/google/firebase/quickstart/analytics/MainActivity.java

Analytics screentracking

---

storage/README.md

These are things that tripped me up when I was going through the quickstart setup.

Adding a couple of details to the setup instructions.

---

analytics/README.md

Update Analytics README

---

README.md

Added instructions on adding sample apps to a Firebase project.

Updated documentation regarding setting up sample apps

---

.travis.yml

Add perf to travis config

---

.travis.yml
mock-google-services.json

1. Add exported licenses that were previously accepted, as documented here: https://developer.android.com/studio/intro/update.html#download-with-gradle
2. Add new client with Perf package name to mock-google-services.json

Fix travis build for Perf

---

admob/build.gradle
analytics/build.gradle
app-indexing/build.gradle
auth/build.gradle
build.gradle
config/build.gradle
crash/build.gradle
database/build.gradle
dynamiclinks/app/build.gradle
dynamiclinks/build.gradle
invites/app/build.gradle
invites/build.gradle
messaging/build.gradle
perf/build.gradle
storage/build.gradle

Lower plugin version to 2.3.3

---

.travis.yml
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/AppIndexingUtil.java

Use sticker builders to define the properties of stickers and
sticker pack.

Use sticker builders.

---

admob/build.gradle
analytics/build.gradle
app-indexing/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/GoogleSignInActivity.java
auth/build.gradle
build.gradle
config/build.gradle
crash/build.gradle
database/build.gradle
dynamiclinks/build.gradle
firestore/build.gradle
invites/build.gradle
messaging/build.gradle
perf/build.gradle
storage/build.gradle

Imported Snackbar class and wrote the update in a cleaner manner

Fixed the issue as advised

---

firestore/README.md
firestore/app/src/main/java/com/google/firebase/example/fireeats/MainActivity.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/util/RestaurantUtil.java
firestore/app/src/main/res/menu/menu_main.xml
firestore/app/src/main/res/values/strings.xml

Remove firestore delete operation from client side

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/MainActivity.java
firestore/app/src/main/res/values/strings.xml

Fix firestore sign-in flow

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java

Changes to add NotificationChannel as this is needed from Oreo for the notification to appear.

Since android Oreo notification channel is needed.

---

auth/app/src/main/AndroidManifest.xml

Pan for phone layout

---

storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MyBaseTaskService.java

Make notifications use channels

---

analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
crash/app/build.gradle
firestore/app/build.gradle
firestore/app/src/main/AndroidManifest.xml
messaging/app/build.gradle
storage/app/build.gradle

Update for M24

---

build.sh
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/CameraSource.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/CameraSourcePreview.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/barcodescanning/BarcodeScanningProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudimagelabeling/CloudImageLabelingProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudlandmarkrecognition/CloudLandmarkRecognitionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudtextrecognition/CloudDocumentTextRecognitionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudtextrecognition/CloudTextRecognitionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/textrecognition/TextRecognitionProcessor.java
mlkit/app/src/main/res/menu/camera_button_menu.xml
mock-google-services.json
settings.gradle

MLKit Build

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/facedetection/FaceDetectionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/facedetection/FaceGraphic.java

I found ML kit provides a real-time 10-points face landmark detection. Why not add it to the demo?

Add face landmark detection in ML kit demo

---

crash/README.md
crash/app/build.gradle
crash/app/src/main/java/com/google/samples/quickstart/crash/MainActivity.java
crash/app/src/main/res/values/strings.xml
crash/build.gradle

Convert crash quickstart to crashlytics

---

mlkit/README.md
mlkit/app/build.gradle
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/CameraSource.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/GraphicOverlay.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/custommodel/CustomImageClassifier.java

- Add noCompress option to build.gradle
- Add calls to register local and hosted model while setting up custom model interpreter.

Updates to the mlkit quickstart for issue #508

---

mlkit/app/build.gradle

If this dependency is not added, a warning will be displayed.

add firebase core dependency

---

app-indexing/README.md

**Copyright 2016 Google, Inc. ---> Copyright 2018 Google, Inc.**

Update License in README.md

---

mlkit/app/build.gradle
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudtextrecognition/CloudDocumentTextGraphic.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudtextrecognition/CloudDocumentTextRecognitionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/cloudtextrecognition/CloudTextRecognitionProcessor.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/textrecognition/TextRecognitionProcessor.java

Reverts firebase/quickstart-android#584

Revert "Revert "MLKit text API update for M30""

---

config/app/build.gradle
config/app/src/androidTest/java/com/google/samples/quickstart/config/MainActivityTest.java
config/app/src/main/AndroidManifest.xml
config/app/src/main/java/com/google/samples/quickstart/config/EntryChoiceActivity.kt
config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
config/app/src/main/java/com/google/samples/quickstart/config/kotlin/MainActivity.kt
config/app/src/main/res/layout/activity_main.xml

feat: Remote Config Quickstart in Kotlin

---

storage/app/build.gradle
storage/app/src/androidTest/java/com/google/firebase/quickstart/firebasestorage/MainActivityTest.java
storage/app/src/main/AndroidManifest.xml
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/EntryChoiceActivity.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MainActivity.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MyBaseTaskService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MyDownloadService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MyUploadService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyBaseTaskService.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyDownloadService.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyUploadService.kt
storage/app/src/main/res/layout/activity_main.xml

Converts storage quickstart to Kotlin

---

messaging/app/build.gradle
messaging/app/src/androidTest/java/com/google/firebase/quickstart/fcm/MainActivityEspressoTest.java
messaging/app/src/main/AndroidManifest.xml
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/EntryChoiceActivity.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MainActivity.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyJobService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MainActivity.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyJobService.kt
messaging/app/src/main/res/layout/activity_main.xml
messaging/app/src/main/res/values/strings.xml

feat : convert fcm quickstarts to kotlin

---

analytics/app/build.gradle
dynamiclinks/app/build.gradle
internal/lintchecks/build.gradle
invites/app/build.gradle

Fix lint build

---

app-indexing/app/build.gradle
app-indexing/app/src/androidTest/java/com/google/samples/quickstart/app_indexing/MainActivityKotlinTest.kt
app-indexing/app/src/androidTest/java/com/google/samples/quickstart/app_indexing/MainActivityTest.java
app-indexing/app/src/androidTest/java/com/google/samples/quickstart/app_indexing/kotlin/MainActivityTest.kt
app-indexing/app/src/main/AndroidManifest.xml
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/EntryChoiceActivity.kt
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/java/AppIndexingService.java
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/java/AppIndexingUtil.java
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/java/MainActivity.java
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/java/StickerProvider.java
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/kotlin/AppIndexingService.kt
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/kotlin/AppIndexingUtil.kt
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/kotlin/MainActivity.kt
app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/kotlin/StickerProvider.kt
app-indexing/app/src/main/res/layout/activity_main.xml

feat : kotlinize app indexing quickstarts

---

mlkit/app/build.gradle

Related issue:
https://github.com/firebase/quickstart-android/issues/700

Fix in mlkit face detection sample app for ears detection (#700)

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java/LivePreviewActivity.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/LivePreviewActivity.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/custommodel/CustomImageClassifier.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/custommodel/CustomImageClassifierProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceContourDetectorProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceContourGraphic.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceDetectionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceGraphic.kt

Kotlinize the new quickstarts added by @gkaldev

feat : kotlinize new MLKit quickstarts

---

build.sh
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/LivePreviewActivity.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/VisionProcessorBase.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/barcodescanning/BarcodeScanningProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/cloudimagelabeling/CloudImageLabelingProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/cloudlandmarkrecognition/CloudLandmarkRecognitionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/cloudtextrecognition/CloudDocumentTextRecognitionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/cloudtextrecognition/CloudTextRecognitionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceContourDetectorProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceDetectionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/imagelabeling/ImageLabelingProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/textrecognition/TextRecognitionProcessor.kt

@samtstern This should fix #720, I tested it on my local devices and the LivePreview activity in Kotlin works without issues now!

fix : fix frozen camera in LivePreview

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/java/FilterDialogFragment.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/java/RatingDialogFragment.java

Correct binding reset in fragments when using ButterKnife.

Appropriate reset unbind to ButterKnife in Fragments

---

analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/CustomAuthActivity.kt
auth/app/src/main/res/values/strings.xml
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/MainActivity.kt
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/RatingDialogFragment.kt
mlkit-smartreply/app/src/main/java/com/google/firebase/samples/apps/mlkit/smartreply/kotlin/chat/ChatFragment.kt
mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateFragment.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyUploadService.kt

Hi I fix some safe Null, order some code and change deprecated code. I will do some more fixes.
Firebase Lover <3

Some deprecated code, order code and safe null fix

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/automl/AutoMLImageLabelerProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/facedetection/FaceDetectionProcessor.kt
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/objectdetection/ObjectDetectorProcessor.kt

fix: change val into a const

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/LivePreviewActivity.kt

refactor: kotlinize LivePreviewActivity

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/ChooserActivity.kt

fixes #968 
This is similar to #964 I forgot to remove this in that PR

refactor: kotlinize ChooserActivity

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/custommodel/CustomImageClassifier.kt

refactor: remove explicit type argument

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt

Reported on https://github.com/firebase/quickstart-android/commit/9753ac35d324440d8d06587c512ac133c7b41bca#r35491446

docs: fix typo on PhoneAuthActivity.kt

---

firestore/app/build.gradle

Reverts firebase/quickstart-android#978

Revert "bump firestore version"

---

admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/kotlin/StickerProvider.kt
auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/ChooserActivity.kt
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
internal/chooserx/build.gradle
internal/lintchecks/build.gradle
messaging/app/build.gradle
mlkit-langid/app/build.gradle
mlkit-smartreply/app/build.gradle
mlkit-translate/app/build.gradle
mlkit/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

Android 10 is here. We should make sure our quickstarts will run on it. :smiley:

chore: update sdk version to 29

---

mlkit/app/build.gradle

We couldn't use `Barcode Detection` sample.
I added dependency of `firebase-ml-vision-barcode-model` v16.0.1 in this Pull Request

Add barcode detection model.

---

auth/README.md
auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GenericIdpActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GenericIdpActivity.kt
auth/app/src/main/res/layout/activity_generic_idp.xml
auth/app/src/main/res/layout/item_spinner_list.xml
auth/app/src/main/res/values/strings.xml

Change generic to use Apple Sign In

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/AnonymousAuthActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt
config/app/src/main/java/com/google/samples/quickstart/config/kotlin/MainActivity.kt
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/MainActivity.kt
inappmessaging/app/src/main/java/com/google/firebase/fiamquickstart/kotlin/KotlinMainActivity.kt
mlkit-smartreply/app/src/main/java/com/google/firebase/samples/apps/mlkit/smartreply/kotlin/chat/ChatViewModel.kt

Sending some minor kotlin improvements I found while navigating our quickstarts.

refactor: make kotlin improvements where possible

---

database/app/src/main/java/com/google/firebase/quickstart/database/java/BaseActivity.java
database/app/src/main/java/com/google/firebase/quickstart/database/java/SignInActivity.java
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/BaseActivity.kt
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/SignInActivity.kt
database/app/src/main/res/layout/activity_sign_in.xml

Follow up to #1010 
Replacing deprecated `ProgressDialog` with `ProgressBar`.

refactor(rtdb): replace ProgressDialog with ProgressBar

---

mlkit/README.md

Add link to the Material Design sample. (To try to ensure that developers know the other exists—it demonstrates how to solve so UI issues in this more straightforward sample.)

Link/reference the MD ML Kit sample

---

admob/app/build.gradle
auth/app/build.gradle
firestore/app/build.gradle

Reverts firebase/quickstart-android#1027

Revert "Auto-update dependencies."

---

crash/README.md

docs(crashlytics): update stackoverflow link on README.md

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/custommodel/CustomImageClassifier.kt

The imgData variable in convertBitmapToByteBuffer function was being assigned a new byte[] each time, and the last used byte[] were not being removed from memory which was causing a memory leak. The variable was made a property of the class and was initiated only once, cleared and reused again.

Remove memory leak from CustomImageClassifier.kt

---

database/app/src/main/java/com/google/firebase/quickstart/database/java/fragment/PostListFragment.java
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/fragment/PostListFragment.kt

Renaming those arguments on the documentation to make it clear what they represent.

refactor(database): rename transactions snippet arguments

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java/ChooserActivity.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/ChooserActivity.kt
mlkit/app/src/main/res/layout/activity_chooser.xml

Small issue in MLKit
cc @rosariopfernandes

Fix ViewBinding build

---

auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/AnonymousAuthActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/CustomAuthActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/EmailPasswordActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GenericIdpActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorEnrollActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorUnenrollActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PasswordlessActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt
database/app/build.gradle
database/app/src/main/java/com/google/firebase/quickstart/database/java/fragment/PostListFragment.java
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/BaseActivity.kt
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/MainActivity.kt
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/SignInActivity.kt
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/fragment/PostListFragment.kt
firestore/app/build.gradle
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainActivity.kt
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/RatingDialogFragment.kt
functions/app/build.gradle
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/MainActivity.kt
storage/app/build.gradle
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt

[Firebase Auth KTX](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/ktx/package-summary) was recently released. This should update our samples to use it instead.
Additionally, on the snippets I've replaced some of the null-safe expressions with `!!` because I'm afraid beginners who copy code from the Documentation might think their code is not being executed, when in reality some properties (like `currentUser`) are null.

refactor(auth): update code to use Firebase Auth KTX

---

database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/NewPostActivity.kt

Just a minor improvement on a RTDB snippet

refactor(database): java's HashMap --> kotlin's hashMapOf()

---

functions/.gitignore
functions/app/src/main/AndroidManifest.xml
functions/app/src/main/res/xml/network_security_config.xml
functions/functions/index.js
functions/functions/package-lock.json
functions/functions/package.json

The JS inside `functions` was stone age.

Update Functions code

---

admob/app/build.gradle
analytics/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
messaging/app/build.gradle
mlkit/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

We're making this the recommended pattern

Use the BoM for all dependencies

---

inappmessaging/app/build.gradle
inappmessaging/app/src/main/java/com/google/firebase/fiamquickstart/java/MainActivity.java
inappmessaging/app/src/main/java/com/google/firebase/fiamquickstart/kotlin/KotlinMainActivity.kt
inappmessaging/app/src/main/res/layout/activity_main.xml
inappmessaging/app/src/main/res/values/strings.xml
messaging/app/build.gradle
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MainActivity.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MainActivity.kt
messaging/app/src/main/res/values/strings.xml
perf/app/build.gradle
perf/app/src/main/java/com/google/firebase/quickstart/perfmon/kotlin/MainActivity.kt

Changes
- Add Perf KTX
- Add Messaging KTX
- Remove uses of FirebaseInstanceId

Add some more KTX libs, use Installations instead of InstanceId

---

messaging/app/build.gradle
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MainActivity.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MainActivity.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt
messaging/app/src/main/res/values/strings.xml

Get FCM reg toke from FCM SDK.

Get token from messaging SDK

---

auth/README.md

fix typos in readme

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/FilterDialogFragment.kt
firestore/app/src/main/res/values/strings.xml

A few fixes, first, it is some useless texts in the strings file (firestore project) and a bug found in the FilterDialog

Josephwambura patch binding bugs

---

admob/app/src/main/res/layout/activity_main.xml
admob/app/src/main/res/layout/second_activity.xml

Kick starting the "jetpackification" with a simple one.
Here are the new layouts:
activity_main.xml
second_activity.xml

refactor(admob): replace RelativeLayout with ConstraintLayout

---

config/app/src/main/res/layout/activity_main.xml

This should bring `ConstraintLayout` to the Remote Config Quickstart. Full discussion in #1217 
Previous layout (RelativeLayout):
New layout:

refactor(config): replace RelativeLayout with ConstraintLayout

---

.opensource/project.json
firestore/README.md
firestore/app/build.gradle
firestore/app/src/main/java/com/google/firebase/example/fireeats/EntryChoiceActivity.kt

Googlers: for context see http://b/176971059

Cloud Firestore --> Firestore

---

.google/packaging.yaml
mlkit/.google/packaging.yaml

Now that the default is 'main' for all branches. I need to change your default branch is master.
I also fixed the MLKit sample which is listed as a separate sample.

Modifies YAML files to work with studio/sample page

---

scripts/checksnippets.py

I guess GitHub actions updated?

Move scripts to python3

---

inappmessaging/README.md

Scope of changes is restricted to docs only. Change is in agreement with Standard American English.

fix(docs): corrects typo in project documentation

---

admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
messaging/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

See https://github.com/firebase/firebase-android-sdk/issues/2721 for the reason

Re order plugins

---

admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
internal/chooserx/build.gradle
internal/lint/build.gradle
internal/lintchecks/build.gradle
messaging/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

New plugin syntax

---

messaging/README.md

fix documentation link in messaging/README.md

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/java/RestaurantDetailFragment.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/RestaurantDetailFragment.kt

Replace `onBackPressed()` method to `popBackStack()`
Closes #1417

:sparkles: feat: replace deprecated navigation method

---

dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/java/MainActivity.java
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
dynamiclinks/app/src/main/res/layout/activity_main.xml
dynamiclinks/app/src/main/res/values/strings.xml

Updates the FDL Quickstart to generate a short dynamic link to have the same behavior as the iOS counterpart.

Adds create short link functionality to FDL quickstart

---

dynamiclinks/app/src/main/res/layout/activity_main.xml

This PR converts the current Nested LinearLayouts to ConstraintLayout.
PS: It also uses a scrollview to allow scrolling for small devices. 
closes #1428

refactor: Convert LinearLayout to ConstraintLayout

---

storage/app/build.gradle
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MainActivity.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MyBaseTaskService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyBaseTaskService.kt
storage/gradle.properties

Tested on Android L (API 22) and Android 12L (API 32)

Fixed crashing of storage app

---

admob/README.md

Update spelling in README.md

---

config/README.md

Update README.md (fix a small typo)

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/EntryChoiceActivity.kt

Unnecessary import has been removed

Remove unnecessary import

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MainActivity.kt

get is Deprecated
so change get -> getString

change deprecated get

---

vertexai/app/build.gradle.kts
vertexai/app/src/main/AndroidManifest.xml
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/GenerativeAiViewModelFactory.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/MainActivity.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/MenuScreen.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/audio/AudioRecorder.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/audio/AudioScreen.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/audio/AudioUiState.kt
vertexai/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/audio/AudioViewModel.kt
vertexai/app/src/main/res/drawable/mic.xml
vertexai/app/src/main/res/drawable/stop.xml
vertexai/app/src/main/res/values/strings.xml

This adds a new feature to the Vertex AI sample app that lets the user record audio and ask the model a question about it.

VertexAI: add audio input feature

---

dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/MainActivity.kt
dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/moviedetail/MovieDetailViewModel.kt
dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/moviedetail/UserReviews.kt
dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/profile/ProfileScreen.kt
dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ReviewCard.kt
dataconnect/app/src/main/res/values/strings.xml

- Remove Actor biography
- Update rating to be out of 10 and limit review characters
- Show movie name in the profile's review card
- Handle movie clicks from profile screen

refactor: improvements for the FDC quickstart

---

functions/functions/index.js
functions/functions/package-lock.json
functions/functions/package.json

Functions v1 have been deprecated for a while, and we should use v2 when writing functions.

Update functions used for testing to be v2

---

functions/app/src/main/java/com/google/samples/quickstart/functions/java/FunctionsMessagingService.java
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/FunctionsMessagingService.kt

This should resolve build errors such as https://github.com/firebase/quickstart-android/actions/runs/15523043974/job/43698815458

refactor(fcm): check for permission before posting notification

---

firebase-ai/gradle/libs.versions.toml

When importing the project directly in AndroidStudio, the dependencies are not found and it fails to build.
Additionally, bump some deps.

Add missing deps to firebase-ai catalog

---

firebase-ai/app/src/main/java/com/google/firebase/quickstart/ai/FirebaseAISamples.kt

update image generation sample to use gemini-2.5-flash-image-preview
