firebase/quickstart-android

.travis.yml
README.md
admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
build.sh
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
invites/app/build.gradle
messaging/app/build.gradle
mock-google-services.json
storage/app/build.gradle

@kroikie please review, and if you choose to merge please use the Gthub 'squash' option.
This does the following:
* Standardize build tools version, ignoring lint, and proguarding release variant
* Add Travis CI configuration:
* On pull requests, do a quick assembleDebug for all folders (~10 min on Travis)
* On merged commits, build the whole thing (~30 min on Travis)
Future work:
* Make the build faster so that we don't ever hit Travis' 50 minute limit.

Travis CI Builds

---

build.sh

The gradle changes in #26 made memory usage increase over Travis' limit, so this controls the heap.

Travis CI memory usage

---

.travis.yml
build.sh

Two improvements:
* Build matrix (thanks @iulukaya !)
* Gradle caching
This gets us down from one big 30-minute build to individual 9-minute builds.
This also opens the door for actually running the tests on Travis!  But I'm not sure if our tests are sufficiently de-flaked for that.

Make travis much faster

---

storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MainActivity.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MyBaseTaskService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MyDownloadService.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MyUploadService.java
storage/app/src/main/res/values/strings.xml

We don't have an example of how to use the internals of the Streaming API. I added code to the upload and download handlers to exemplify how a developer could use the process data that we provide.

Showcasing the Streaming download API to indicate progress

---

admob/build.gradle
analytics/build.gradle
app-indexing/build.gradle
build.gradle
config/build.gradle
crash/build.gradle
database/build.gradle
dynamiclinks/build.gradle
invites/build.gradle
messaging/build.gradle
perf/build.gradle
storage/build.gradle

[Android Studio 2.3.2 is now available in the stable channel](https://androidstudio.googleblog.com/2017/05/android-studio-232-is-now-available-in.html) and the Android Gradle plugin has been updated to `2.3.2` as well.

Update Android Gradle plugin to 2.3.2

---

messaging/README.md
messaging/app/src/main/AndroidManifest.xml

There is incorrect metadata name for default notification channel. I've posted [stackoverflow question](https://stackoverflow.com/questions/45995337/firebase-messaging-default-notification-channel-doesnt-work) and got answer from Diego Giorgini. So here is fix.

fixed metadata name for default notification channel

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java

Example method `sendNotification` uses deprecated notification builder constructor (without specified notification channel). So if we'll use this method on Android O - notifications won't show up.

added default channel parameter when constructing own notification

---

storage/app/build.gradle
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/MyUploadService.java

The previous method was deprecated in `15.0.0`

Stop using downloadURL property from Task Snapshot

---

admob/build.gradle
analytics/build.gradle
app-indexing/build.gradle
auth/build.gradle
build.gradle
config/build.gradle
crash/build.gradle
database/build.gradle
dynamiclinks/build.gradle
firestore/app/build.gradle
firestore/build.gradle
functions/build.gradle
invites/build.gradle
messaging/build.gradle
perf/build.gradle

Details:
We use the quick start repos to test release candidates by having
these masquerade as artifacts that they serve to demonstrate.
Gradle looks for dependencies through repositories in the order in
which they are listed.
We put mavel local over all other repos to allow artifacts to be
published into mavenLocal and masqeuerade as existing versions
for testing.

Change the order of repos used by modules

---

firestore/app/src/androidTest/java/com/google/firebase/example/fireeats/MainActivityTest.java

When running against the default emulator skin, the soft keyboard
overlays the password done button causing test failure. Adding to the
email input view as well as future-proofing.

Close keyboard in Firestore espresso test.

---

firestore/app/build.gradle
firestore/app/src/androidTest/AndroidManifest.xml
firestore/app/src/androidTest/java/com/google/firebase/example/fireeats/MainActivityTest.java
firestore/app/src/main/AndroidManifest.xml
functions/app/build.gradle
functions/app/src/androidTest/AndroidManifest.xml
functions/app/src/androidTest/java/com/google/samples/quickstart/functions/TestAddNumber.java

UI tests now run ~twice as fast, while providing more generous individual timeouts.
Also avoids the need to add IdlingResources (or even progress indicators) to the quickstart apps.

Rewrite Espresso tests with UIAutomator: no sleep!

---

firestore/app/src/androidTest/java/com/google/firebase/example/fireeats/MainActivityTest.java

We're seeing extreme flakiness with 30s timeouts, so this should do the trick. Hopefully.

Extend UIAutomator timeouts.

---

mlkit/build.gradle

I think this setting is not appropriate because it depends on the directory of a specific user.

MLKit sample: Remove inappropriate local repository setting

---

functions/app/build.gradle
functions/app/src/androidTest/java/com/google/samples/quickstart/functions/MainActivityTest.java
functions/app/src/androidTest/java/com/google/samples/quickstart/functions/TestAddNumber.java
functions/app/src/main/AndroidManifest.xml
functions/app/src/main/java/com/google/samples/quickstart/functions/EntryChoiceActivity.kt
functions/app/src/main/java/com/google/samples/quickstart/functions/java/FunctionsMessagingService.java
functions/app/src/main/java/com/google/samples/quickstart/functions/java/MainActivity.java
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/FunctionsMessagingService.kt
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/MainActivity.kt
functions/app/src/main/res/layout/activity_main.xml
internal/build.gradle

feat: Functions Quickstart Kotlin

---

crash/app/build.gradle
crash/app/src/androidTest/java/com/google/samples/quickstart/crash/MainActivityTest.java
crash/app/src/main/AndroidManifest.xml
crash/app/src/main/java/com/google/samples/quickstart/crash/EntryChoiceActivity.kt
crash/app/src/main/java/com/google/samples/quickstart/crash/java/MainActivity.java
crash/app/src/main/java/com/google/samples/quickstart/crash/kotlin/MainActivity.kt
crash/app/src/main/res/layout/activity_main.xml

feat : kotlinize crash quickstart

---

internal/lint/src/main/java/com/firebase/lint/InvalidImportDetector.kt
internal/lint/src/test/java/com/firebase/lint/InvalidImportDetectorTest.kt

@the-dagger did a few things here:
1. We had the linter backwards!  It was looking for `kotlin` imported by `java` not the other way around.
2. Made it an error.

Fix linter, increase severity

---

auth/README.md
auth/app/src/main/AndroidManifest.xml

Looks like we were trying to catch the continueUrl and that doesn't work. We can either catch the dynamic link domain or email action handler url. Also, we can't use pathPrefix to distinguish between links. 
This is for https://github.com/firebase/quickstart-android/issues/488

Email link fixes

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/cloudimagelabeling/CloudImageLabellingProcessor.kt

- Lint-warning at `onSuccess()`
- `detector` with `by-lazy`. 
- I know people will mind there's no need for performance improvement here, however, for enthusiast :)

Fix lint warnings and optimize for CloudImageLabelingProcessor

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/common/CameraSource.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java/LivePreviewActivity.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/LivePreviewActivity.kt

Proposed solution for #748 
*  Detects that there is a single camera on the device and removes the toggle button from the UI when creating the LivePreview activity (both Java and Kotlin)
*  Detects single camera configuration within CameraSource and forces the facing variable to be equal to the value within CameraInfo
Camera enumeration and meta-data require `android.permission.CAMERA`  in the manifest, but do not require the user to approve the `Camera` runtime permission - making the calls used in `onCreate` to determine the toggle button safe to perform prior to validating runtime permissions.

[mlkit] Single Camera Handling

---

firestore/app/proguard-rules.pro

Without these changes, the app crashes on (approx) startup when in
release mode.

Fix proguard rules to work with java/kotlin split.

---

messaging/README.md
messaging/app/src/main/AndroidManifest.xml
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt

* Set FirebaseMessagingServices to exported="false" to explicitly
prevent other apps from being able to send messages to it.
* Fixed documentation to indicate to remove the Kotlin service
intent filter for Java now that the Kotlin service is first in the
manifest.

Make FirebaseMessagingServices not exported

---

perf/app/build.gradle

Demonstrate how to enable/disable performance monitoring Gradle plugin for a specific build variant.

Add flag to enable/disable performance monitoring plugin

---

config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
config/app/src/main/java/com/google/samples/quickstart/config/kotlin/MainActivity.kt

Switch to the recommended async methods for setting Remote Config settings and defaults.

Switch from deprecated config methods

---

app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/java/AppIndexingService.java
app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/java/AppIndexingUtil.java

`AppIndexingService`'s call to `AppIndexingUtil#setStickers` is asynchronous, but `IntentService#onHandleIntent` is a synchronous method, so we must return the `Task<Void>` from `AppIndexingUtil#setStickers` and block `onHandleIntent` until the `setStickers` `Task<Void>` completes.

Blocked on setStickers call

---

auth/app/src/androidTest/java/com/google/firebase/quickstart/auth/BaseActivityIdlingResource.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/AnonymousAuthActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/BaseActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/EmailPasswordActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FacebookLoginActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GoogleSignInActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PasswordlessActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/AnonymousAuthActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/BaseActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/EmailPasswordActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PasswordlessActivity.kt
auth/app/src/main/res/layout/activity_anonymous_auth.xml
auth/app/src/main/res/layout/activity_emailpassword.xml
auth/app/src/main/res/layout/activity_facebook.xml
auth/app/src/main/res/layout/activity_google.xml
auth/app/src/main/res/layout/activity_passwordless.xml

[ProgressDialog](https://developer.android.com/reference/android/app/ProgressDialog) has been deprecated in API 26. This PR should replace its usage on the auth quickstart with a ProgressBar.
Here's how it looks now:
I'll also send follow-up PRs to replace it in:

refactor(auth): replace ProgressDialog with ProgressBar

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/java/AnonymousAuthActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/BaseActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/EmailPasswordActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FacebookLoginActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GenericIdpActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GoogleSignInActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PasswordlessActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/AnonymousAuthActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/BaseActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/EmailPasswordActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GenericIdpActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PasswordlessActivity.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MainActivity.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt
storage/app/src/main/res/layout/activity_main.xml

Follow up to #1010 
Replacing deprecated `ProgressDialog` with `ProgressBar` on the storage quickstart.
Update: using this same PR to update auth's `showProgressDialog()` and `hideProgressDialog()` to `showProgressBar()` and `hideProgressBar()` respectively.

refactor(storage): replace ProgressDialog with ProgressBar

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java/StillImageActivity.java
mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/StillImageActivity.kt

Starting in API 29, [MediaStore.Images.Media.getBitmap()](https://developer.android.com/reference/android/provider/MediaStore.Images.Media.html#getBitmap(android.content.ContentResolver,%2520android.net.Uri)) has been deprecated. The docs recommend using [ImageDecoder.createSource()](https://developer.android.com/reference/android/graphics/ImageDecoder.html#createSource(android.content.ContentResolver,%2520android.net.Uri)) instead. This PR should make that replacement and (also in `StillImageActivity`):
- replace `Math.max()` with kotlin's `max()`;
- make `getImageButton` a local variable;
- remove unused variable `bitmapForDetection`.
Fixes #912

refactor(mlkit): use ImageDecoder.decodeBitmap() on API >= 29

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GenericIdpActivity.kt

- This  **enormous** 🎉 pull request fixes a typo in the provider mapping for Apple causing the Kotlin version of `GenericIdp` to never successfully log in.

Fix provider for Apple in Kotlin version

---

analytics/app/build.gradle
analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt

As mentioned in the [documentation](https://developer.android.com/reference/android/preference/PreferenceManager), `android.preference.PreferenceManager` has been deprecated in favor of `androidx.preference.PreferenceManager`. This PR should address that in our analytics sample app.

refactor(analytics): use androidx preference library

---

firestore/app/build.gradle
firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainActivity.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainActivity.kt

Another one on the deprecation saga. 
This PR should replace the deprecated [`Html.fromHtml()`](https://developer.android.com/reference/android/text/Html.html#fromHtml(java.lang.String)) method with `HtmlCompat.fromHtml()`, as recommended on this [post](https://stackoverflow.com/a/37905107/5861618).

refactor(firestore): Html --> HtmlCompat

---

internal/lint/src/test/java/com/firebase/lint/InvalidImportDetectorTest.kt

Call `allowMissingSdk()` in `InvalidImportDetectorTestCall.kt` to avoid the following error ...
```
java.lang.AssertionError: This test requires an Android SDK: No SDK configured.
```
... and make tests pass.

Fix failing tests in InvalidImportDetectorTestCall.kt

---

mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java/custommodel/CustomImageClassifier.java

The imgData variable in convertBitmapToByteBuffer function was being assigned a new byte[] each time, and the last used byte[] were not being removed from memory which was causing a memory leak. The variable was made a property of the class and was initiated only once, cleared and reused again.

Remove memory leak from CustomImageClassifier.java

---

dynamiclinks/app/build.gradle
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt

This PR should convert the Dynamic Links sample in #1063 to KTX.
The `dynamic-links-ktx` library was released last friday and the docs are yet to be added to firebaseopensource.com (see firebase/firebase-android-sdk/pull/971)

Dynamic Links + KTX

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainActivity.java
mlkit-smartreply/app/src/main/java/com/google/firebase/samples/apps/mlkit/smartreply/java/chat/ChatFragment.java
mlkit-smartreply/app/src/main/java/com/google/firebase/samples/apps/mlkit/smartreply/kotlin/chat/ChatFragment.kt
mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/java/TranslateFragment.java
mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateFragment.kt

Starting in version 2.2.0 of the lifecycle library, the [ViewModelProviders](https://developer.android.com/reference/kotlin/androidx/lifecycle/ViewModelProviders) class has been deprecated. We should now use the [ViewModelProvider](https://developer.android.com/reference/androidx/lifecycle/ViewModelProvider) constructor instead.

refactor: ViewModelProviders --> ViewModelProvider

---

admob/app/build.gradle
admob/app/src/androidTest/java/com/google/samples/quickstart/admobexample/InterstitialAdTest.java
analytics/app/build.gradle
analytics/app/src/androidTest/java/com/google/firebase/quickstart/analytics/MainActivityTest.java
app-indexing/app/build.gradle
app-indexing/app/src/androidTest/java/com/google/samples/quickstart/appindexing/MainActivityTest.java
app-indexing/app/src/androidTest/java/com/google/samples/quickstart/appindexing/kotlin/MainActivityTest.kt
config/app/build.gradle
config/app/src/androidTest/java/com/google/samples/quickstart/config/MainActivityTest.java
crash/app/build.gradle
crash/app/src/androidTest/java/com/google/samples/quickstart/crash/MainActivityTest.java
dynamiclinks/app/build.gradle
dynamiclinks/app/src/androidTest/java/com/google/firebase/quickstart/deeplinks/MainActivityTest.java

`androidx.test.runner.AndroidJUnit4` is now deprecated in favor of `androidx.test.ext.junit.runners.AndroidJUnit4`. This PR should update our tests to use the new class instead.
Additionally, it should replace the deprecated functions `Espresso.registerIdlingResources()` and `Espresso.unregisterIdlingResources()` with `IdlingRegistry.getInstance().register()` and `IdlingRegistry.getInstance().unregister()` respectively.

test: replace deprecated AndroidJUnit4

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GoogleSignInActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt

The main reason why I've opened this PR is to change the `firebaseAuthWithGoogle()` function to take a googleIdToken (`String`) as argument instead of `GoogleSignInAccount`. Since some Auth libraries like [One Tap UI](https://developers.google.com/identity/one-tap/android/get-saved-credentials#sign_in_with_retrieved_credentials) actually return google id tokens, we could reuse the `firebaseAuthWithGoogle()` method to handle both: a simple google sign in and a google sign with One Tap UI.
---
Additionally, I've found a few smaller issues and I fixed them:
- some Kotlin function declarations had `public` on their signature
- the `binding` property was exposed in a snippet

refactor(auth): change firebaseAuthWithGoogle() argument type

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt

The way it's currently written, the `let` block will always be called regardless of whether `isNotEmpty` returns `true` or `false`.
Update: I also noticed we could've used a string template instead of concatenation on the same method. I pushed a new commit changing it.

fix(messaging): fix wrong nullability check on MessagingService

---

admob/app/build.gradle
analytics/app/build.gradle
app-indexing/app/build.gradle
auth/app/build.gradle
config/app/build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
messaging/app/build.gradle
mlkit/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

Starting in Kotlin 1.4.0, the kotlin-stdlib is [added by default](https://kotlinlang.org/docs/reference/whatsnew14.html#dependency-on-the-standard-library-added-by-default). So we no longer need it on our build.gradle files.

chore(*): remove kotlin-stdlib-jdk7 dependency

---

admob/app/src/main/java/com/google/samples/quickstart/admobexample/java/MainActivity.java
admob/app/src/main/java/com/google/samples/quickstart/admobexample/kotlin/MainActivity.kt
analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt

This PR should replace 2 deprecated methods:
1. [`MobileAds.initialize()`](https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-void-initialize-context-context,-string-applicationcode) in the admob sample app;
2. [`FirebaseAnalytics.setCurrentScreen()`](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setCurrentScreen(android.app.Activity,%20java.lang.String,%20java.lang.String)) in the analytics sample app.
Worth pointing out that the analytics snippet is shown in the [Documentation](https://firebase.google.com/docs/analytics/screenviews#kotlin+ktx) and a change may be in order to remove this last line bellow the snippet:

refactor(admob, analytics): replace deprecated methods

---

storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyDownloadService.kt
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MyUploadService.kt

This PR should update our storage sample app to use the Kotlin Destructuring Declarations introduced in `storage-ktx:19.2.0`.
It also fixes a couple of warnings on `MyUploadService.kt`:
- The `Service` import is redundant.
- `Log.d()` can use String template instead of String concatenation.

refactor(storage): use the new Kotlin Destructuring Declarations

---

auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PhoneAuthActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt

Explicitly specific activity for callback binding, use PhoneAuthOptions

Quickstart updates

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/ChooserActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorActivity.kt
auth/app/src/main/res/layout/activity_chooser.xml

Fixing 2 errors here:
- `setContentView()` was being called with the wrong argument in ChooserActivity, causing the `ListView` to not be shown
- On MultiFactorActivity, `setContentView()` was being called with an incompatible `View`, causing the app to crash.
This PR should also remove the padding around the ListView in ChooserActivity and replace its `LinearLayout` with a `FrameLayout`.

refactor(auth): fix kotlin errors and improve chooser layout

---

functions/README.md

The StackOverflow URL in our functions README.md was incorrect.

docs(functions): fix StackOverflow url in README.md

---

perf/app/build.gradle
perf/app/src/main/java/com/google/firebase/quickstart/perfmon/java/MainActivity.java
perf/app/src/main/java/com/google/firebase/quickstart/perfmon/kotlin/MainActivity.kt

This should replace 2 deprecations:
- `AsyncTask`
- In the Java quickstart, I replaced it with `Executors.newSingleThreadExecutor()`.
- In the Kotlin quickstart, I replaced it with a Kotlin Coroutine which I'm launching with the helper `lifecycleScope` KTX from the `lifecycle-runtime-ktx` library.
- `Tasks.call()` - replaced with a `TaskCompletionSource<T>`.

refactor(perfmon): replace deprecated AsyncTask and Tasks.call()

---

database/app/build.gradle
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/viewholder/PostViewHolder.kt
firestore/app/build.gradle

Seems like we missed 2 quickstarts when removing Kotlin Synthetic Binding, which is [now deprecated](https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html).

refactor(database, firestore): remove kotlin synthetic binding

---

app-indexing/app/src/main/res/layout/activity_main.xml

Another quickstart using `ConstraintLayout`: App Indexing.
See discussion in #1217 
Previous layout (RelativeLayout):
New layout:

refactor(app-indexing): replace RelativeLayout with ConstraintLayout

---

crash/app/src/main/res/layout/activity_main.xml
functions/app/src/main/res/layout/activity_main.xml

This should bring ConstraintLayout to our Crashlytics and Cloud Functions quickstarts.
Full discussion in #1217 
Crashlytics:
Cloud Functions:

refactor(crash, functions): replace RelativeLayout with ConstraintLayout

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java

Given the lengthy history of obtaining the token from C2DM, GCM, FCM, and the transition from InstanceID to Installation SDK, added additional clarity to outline all the known scenarios onNewToken is called to match with the details from https://firebase.google.com/docs/cloud-messaging/android/client#sample-register
Attempting to prevent reading multiple blog posts and docs to understand when to use the method in the sample and rather incorporate the latest known information into the sample by updating the previous comments to the latest information

Updated comments for more clarity on when onNewToken is called

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/java/MultiFactorActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PasswordlessActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PhoneAuthActivity.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PasswordlessActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt
auth/app/src/main/res/layout/activity_anonymous_auth.xml
auth/app/src/main/res/layout/activity_emailpassword.xml
auth/app/src/main/res/layout/activity_facebook.xml
auth/app/src/main/res/layout/activity_firebase_ui.xml
auth/app/src/main/res/layout/activity_generic_idp.xml
auth/app/src/main/res/layout/activity_google.xml
auth/app/src/main/res/layout/activity_multi_factor.xml
auth/app/src/main/res/layout/activity_passwordless.xml
auth/app/src/main/res/layout/activity_phone_auth.xml

See discussion in #1217 
**~This is a Work-In-Progress:~**
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>
I changed this one to give it a better look because the …

refactor(auth): remove RelativeLayout usage

---

analytics/app/src/main/res/layout/fragment_main.xml
auth/app/src/main/res/layout/activity_generic_idp.xml

Part of #1217 
Seems like I had missed a layout when working on #1237 and discovered analytics was also using `RelativeLayout`.
<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr><td>
</td><td>
</td></tr></tbody></table>

refactor(auth, analytics): remove RelativeLayout from xml files

---

admob/app/src/main/java/com/google/samples/quickstart/admobexample/java/MainActivity.java
admob/app/src/main/java/com/google/samples/quickstart/admobexample/kotlin/MainActivity.kt
admob/app/src/main/res/layout/activity_main.xml
admob/app/src/main/res/navigation/nav_graph_java.xml
admob/app/src/main/res/navigation/nav_graph_kotlin.xml

I noticed I made a mistake when I sent #1247 : I only added the Kotlin Fragments to the navigation graph, which caused the java ones to never be used.
As a solution (in this PR), I've created a separate nav graph file for the java fragments (`nav_graph_java.xml`) and the graphs are now set programmatically (instead of setting it in the XML layout).

refactor(admob): create a separate nav graph for the java sample

---

app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/java/AppIndexingService.java
app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/java/MainActivity.java
app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/kotlin/AppIndexingService.kt
app-indexing/app/src/main/java/com/google/samples/quickstart/appindexing/kotlin/MainActivity.kt

Staring in [App Indexing 19.2.0](https://firebase.google.com/support/release-notes/android#app-indexing_v19-2-0), `getInstance()` has been deprecated in favor of `getInstance(Context)`.

refactor(app-indexing): update to 19.2.0

---

crash/app/build.gradle
crash/app/src/main/AndroidManifest.xml
crash/app/src/main/java/com/google/samples/quickstart/crash/java/CustomKeySamples.java
crash/app/src/main/java/com/google/samples/quickstart/crash/java/MainActivity.java
crash/app/src/main/java/com/google/samples/quickstart/crash/kotlin/CustomKeySamples.kt
crash/app/src/main/java/com/google/samples/quickstart/crash/kotlin/MainActivity.kt

Add a variety of common custom keys stored on Android that can help developers better diagnose their crashes.

Add examples of custom keys

---

crash/app/src/main/java/com/google/samples/quickstart/crash/java/CustomKeySamples.java
crash/app/src/main/java/com/google/samples/quickstart/crash/java/MainActivity.java
crash/app/src/main/java/com/google/samples/quickstart/crash/kotlin/CustomKeySamples.kt
crash/app/src/main/java/com/google/samples/quickstart/crash/kotlin/MainActivity.kt

(Address Feedback from Marc Richards)
- Add handling for deregistering the network state handler
- Give an example of deregistering within an activity.
(one might consider registering within the application level of the class, as well)

Improve threading for crashlytics network state tracking example

---

firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainFragment.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainFragment.kt

The option menu was not showing up in the Firestore sample since it got refactored to use Fragments and Navigation.

Fix option menu not showing up

---

admob/gradle.properties
analytics/gradle.properties
app-indexing/gradle.properties
auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FacebookLoginFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginFragment.kt
auth/gradle.properties
config/gradle.properties
crash/gradle.properties
database/gradle.properties
dynamiclinks/gradle.properties
firestore/app/build.gradle
firestore/gradle.properties
functions/gradle.properties
gradle.properties
inappmessaging/app/build.gradle
inappmessaging/gradle.properties
messaging/app/build.gradle
messaging/gradle.properties
perf/app/build.gradle
perf/app/src/main/java/com/google/firebase/quickstart/perfmon/java/MainActivity.java
perf/app/src/main/java/com/google/firebase/quickstart/perfmon/kotlin/MainActivity.kt
perf/gradle.properties
storage/gradle.properties

The main goal of this PR is to disable Jetifier in our project.
In order to make that happen, I also had to:
- upgrade facebook sdk to v8.1.0
- upgrade glide version (4.x)
- update workmanager to v2.5.0
- declare picasso 2.8 explicitly to be used in the FIAM quickstart

chore(*): disable jetifier

---

.github/workflows/android.yml

I believe the main reason why we had the Android NDK on our workflow was for the ML Kit samples to build.
Since these samples are now gone we no longer need the NDK on our CI.

chore: remove NDK installation from GitHub Actions workflow

---

auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FirebaseUIFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIFragment.kt
firestore/app/build.gradle
firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainFragment.java
firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainFragment.kt
functions/app/build.gradle
functions/app/src/main/java/com/google/samples/quickstart/functions/java/MainActivity.java
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/MainActivity.kt
storage/app/build.gradle
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MainActivity.java
storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/kotlin/MainActivity.kt

This PR should update `firebase-ui-auth` to `7.2.0` in order to use the new `ActivityResultLauncher` API instead of the deprecated `startActivityForResult()`.

refactor(auth, functions, firestore, storage): use ActivityResultLauncher

---

admob/build.gradle
analytics/build.gradle
app-indexing/build.gradle
auth/build.gradle
build.gradle
config/build.gradle
crash/build.gradle
database/build.gradle
dynamiclinks/build.gradle
firestore/build.gradle
functions/build.gradle
inappmessaging/build.gradle
messaging/build.gradle
perf/build.gradle
storage/build.gradle

`jcenter` has been sunset. This PR should replace it with `mavenCentral` on our project.

chore(*): replace jcenter() with mavenCentral()

---

messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt

`WorkManager.getInstance()` has been deprecated in favor of `WorkManager.getInstance(context)`

refactor(fcm): WorkManager.getInstance() --> WorkManager.getInstance(context)

---

database/app/src/main/java/com/google/firebase/quickstart/database/java/MainFragment.java
database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/MainFragment.kt
database/app/src/main/res/layout/fragment_main.xml

`FragmentPagerAdapter` from the `ViewPager` class has been deprecated and the [reference docs](https://developer.android.com/reference/androidx/fragment/app/FragmentPagerAdapter) suggests migrating to ViewPager2.
This PR should migrate our database module to not use the deprecated FragmentPagerAdapter.

refactor(database): migrate to viewpager2

---

database/app/proguard-rules.pro

Fixes (partially) #1355 
Running the `release` variant of our database quickstart crashes right after auth, due to missing kotlin model classes.
I can see in our `proguard-rules.pro` file that we have a rule to keep the java models, but it seems like we forgot to also add a rule to keep the kotlin models when we created them in #654

refactor(database): add proguard rule to keep kotlin models in release build

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FirebaseUIFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIFragment.kt

Fragments must call registerForActivityResult() before they are created. Use registerForActivityResult() fragment version instead of calling   requireActivity().registerForActivityResult()

Fix launch FirebaseAuthUIActivity crash java and kotlin code

---

auth/app/build.gradle
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GoogleSignInFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInFragment.kt
auth/app/src/main/res/layout/fragment_google.xml
auth/app/src/main/res/values/strings.xml

This PR should:
- Use the new ActivityResultContracts API on Firebase Auth with Google
- Migrate from Google Sign-in to Google Identity Services
TODO:
**Update:** GIS team confirmed this feature was intentionally left out. This PR removes the revoke access button.

Replace Google Sign In with Google Identity Services

---

auth/README.md
auth/app/build.gradle
auth/app/src/main/AndroidManifest.xml
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/FacebookLoginFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginFragment.kt
auth/app/src/main/res/values/ids.xml

The Facebook Android SDK has been updated and the previous versions no longer work.
This PR should:
- update the facebook sdk version on our project
- remove the deprecated `onActivityResult` method
- update the README.md

update facebook sdk to version 13.2.0

---

dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt

This is a workaround for firebase/firebase-android-sdk#2992

explicitly specify PendingDynamicLinkData's nullability

---

functions/app/build.gradle
functions/app/src/main/java/com/google/samples/quickstart/functions/java/MainActivity.java
functions/app/src/main/java/com/google/samples/quickstart/functions/kotlin/MainActivity.kt
messaging/app/build.gradle
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MainActivity.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MainActivity.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/kotlin/MyFirebaseMessagingService.kt

Starting in API Level 31, Notifications' Pending Intent should use `PendingIntent.FLAG_IMMUTABLE`.
Starting in API Level 33, apps should explicitly request the `POST_NOTIFICATION` permission as shown in our [docs](https://firebase.google.com/docs/cloud-messaging/android/client#request-permission13).

FCM updates for API levels 31 and 33

---

admob/app/build.gradle
analytics/app/build.gradle
appdistribution/app/build.gradle
auth/app/build.gradle
build.gradle
crash/app/build.gradle
database/app/build.gradle
dynamiclinks/app/build.gradle
firestore/app/build.gradle
functions/app/build.gradle
inappmessaging/app/build.gradle
messaging/app/build.gradle
perf/app/build.gradle
storage/app/build.gradle

This PR should add jetpack compose dependencies to all the quickstarts' build.gradle files to make it easier to adopt compose.

chore(*): add jetpack compose dependencies

---

auth/app/src/main/java/com/google/firebase/quickstart/auth/java/MultiFactorEnrollFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorEnrollFragment.kt

Issue: MFA Enroll flow in Firebase Auth Quickstart does not work. Enrolling MFA fails with a null pointer exception:
`java.lang.NullPointerException: You must specify an Activity on your PhoneAuthOptions. Please call #setActivity()`
Action: Fixed by calling setActivity() in PhoneAuthOptions.

setActivity for PhoneAuthOptions in MFA Enroll

---

auth/app/src/main/res/layout/fragment_generic_idp.xml

The `@id/detail` TextView is hidden when the Generic Idp Fragment is launched, which causes the Views constrainted to that TextView to be out of place.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/16766726/214152276-777f3845-3670-4955-8e84-780ee3ed02c5.png" width="240px"></td>
<td><img src="https://user-images.githubusercontent.com/16766726/214152286-eba0365c-90b7-46eb-871b-61938ada717e.png" width="240px"></td>
</tr>
</table>

refactor(auth): fix generic idp provider spinner not showing

---

build.gradle

The ktlint library we're using at the moment is no longer maintained, meaning that newer Kotlin features such as trailing commas are being marked as errors by the linter (see [example build failure](https://github.com/firebase/quickstart-android/actions/runs/4050382926/jobs/6967720321) from #1453).
Pinterest forked ktlint and continued development - their fork still uses the same MIT License as the original project, so it should be fine for us to use here.
This PR migrates to the fork and uses the latest version of the ktlint library.

chore: update ktlint 0.31.0 --> 0.48.2

---

admob/app/src/main/java/com/google/samples/quickstart/admobexample/EntryChoiceActivity.kt
auth/app/src/main/java/com/google/firebase/quickstart/auth/EntryChoiceActivity.kt
crash/app/src/main/java/com/google/samples/quickstart/crash/EntryChoiceActivity.kt
functions/app/src/main/java/com/google/samples/quickstart/functions/EntryChoiceActivity.kt
messaging/app/src/main/java/com/google/firebase/quickstart/fcm/EntryChoiceActivity.kt

Currently, if you look at all EntryChoiceActivity, most of them use unifying MainActivity.
And in some apps, you can also see that it's divided into MainActivity and Kotlin MainActivity
I thought if it wasn't named like the picture below, I might be confused if it was java or kotlin or both Kotlin MainActivity.
<br/>
So I unified the import so that developers could easily tell if it was java's MainActivity or Kotlin's MainActivity.

unified imports

---

dynamiclinks/app/build.gradle
dynamiclinks/app/src/main/AndroidManifest.xml
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/EntryChoiceActivity.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/java/MainActivity.java
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/DynamicLinksViewModel.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainComposeActivity.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/ui/theme/Color.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/ui/theme/Shape.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/ui/theme/Theme.kt
dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/ui/theme/Type.kt
dynamiclinks/build.gradle
dynamiclinks/gradle.properties

For review by Rosário Fernandes
- Add Jetpack Compose option in `EntryChoiceActivity` 
- Removed business logic from `MainActivity`
- Added `DynamicLinksViewModel` for business logic
- Added `MainComposeActivity` for the Jetpack Compose UI

Compose Firebase Dynamic Links

---

build.gradle.kts

This should prevent DPE Bot from opening issues like #1537 :
This is a temporary fix until we update to ktlint-cli 1.0

prevent ktlint from being updated

---

analytics/app/build.gradle.kts
analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
inappmessaging/app/build.gradle.kts
inappmessaging/app/src/main/java/com/google/firebase/fiamquickstart/kotlin/KotlinMainActivity.kt

Now that firebase/firebase-android-sdk#5457 has been fixed, we can finally migrate analytics out of ktx

refactor(analytics, fiam): use BoM 32.5.0 and drop ktx

---

.github/workflows/android.yml

Trying to address #1491 
This PR should:
- Replace `gradle build` with `gradle assemble` in CI
Realistically we don't need to build the whole project. We're mostly interested in making sure that the project compiles (we have very few automated tests).
- Add the gradle-build action to enable Gradle cache.
- Update actions/checkout to v4
- Update actions/setup-java to v3

ci: run gradle assemble instead of build

---

messaging/app/build.gradle.kts

This workaround was added in #1534 due to an issue in the analytics SDK. Said issue seems to have been fixed in `firebase-analytics:21.5.0` as explained in https://github.com/firebase/firebase-android-sdk/issues/5467

chore(fcm): remove guava dependency

---

functions/firebase.json

In relation to firebase-tools 13.0.0 breaking change https://github.com/firebase/firebase-tools/pull/6555, Firebase CLI will only reserve functions directory when there is a functions configuration entry in firebase.json that does not specify the source directory.

Configuration of firebase.json due to firebase tools 13.0.0 breaking change

---

build.gradle.kts

Firebase has started to release `alpha` and `beta` artifacts. We should let the bot update these dependencies to keep our quickstarts up to date.

chore(*): allow alpha and beta updates for Firebase libraries

---

appdistribution/app/build.gradle
appdistribution/app/src/main/AndroidManifest.xml
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/EntryChoiceActivity.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/kotlin/AppDistributionViewModel.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/kotlin/ComposeMainActivity.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/ui/theme/Color.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/ui/theme/Shape.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/ui/theme/Theme.kt
appdistribution/app/src/main/java/com/google/firebase/appdistributionquickstart/ui/theme/Type.kt
appdistribution/build.gradle
appdistribution/gradle.properties

- Added Jetpack Compose option in `EntryChoiceActivity`
- Added `ComposeMainActivity`
- Added AppDistribution for business logic
- Added `AppDistributionViewModel`
- Added `ComposeMainActivity` in `AndroidManifest`

Compose code for App Distribution

---

dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ReviewCard.kt
gradle/libs.versions.toml

This PR upgrades the `firebase-dataconnect` dependency to version to `16.0.0-beta03` (https://firebase.google.com/support/release-notes/android#data-connect_v16-0-0-beta03) from `16.0.0-beta02`.
This upgrade is a breaking change and requires Data Connect toolkit version 1.7.0 or later, which is available in firebase-tools version 13.25.0 (https://firebase.google.com/support/release-notes/cli#version_13250_-_november_12_2024). The breaking change is that the code generation for `Date` GraphQL fields and variables uses the new `com.google.firebase.dataconnect.LocalDate` class instead of `java.util.Date`. This new class has functions to convert it to `java.time.LocalDate` and `kotlinx.datetime.LocalDate`.
Since `java.time.LocalDate` was added to the Android standard library in API 26, …

Upgrade firebase-dataconnect version to 16.0.0-beta03 (was 16.0.0-beta02)

---

admob/README.md
appdistribution/README.md

This pull request includes minor corrections to the documentation files for `admob` and `appdistribution` modules. The changes fix typos and improve clarity.
Documentation corrections:
* [`admob/README.md`](diffhunk://#diff-6ab894215d4a4910fc22dfd626eb3a937173eef941b87c06a5f812b1b096ca38L21-R21): Corrected a typo in the description of the running sample.
* [`appdistribution/README.md`](diffhunk://#diff-f02e0d087507f89b028b593059b5ee87ccf64fe64c6132732d9f73a09f4d7a32L1-R1): Fixed a typo in the title of the document.

fix: correct typos in README files.

---

functions/app/build.gradle.kts

dpebot keeps trying to bump the Firebase BoM in the Functions quickstart, but runs into a build error due to firebase/firebase-android-sdk#6522
This PR should pin the Functions SDK version to the last working one before the break.
Once a new version of functions comes out with the fix for firebase/firebase-android-sdk#6522 we should revert this change.

pin the Functions SDK version

---

build.gradle.kts

This should be reverted at the same time as #2640

add firebase-functions to list of blocklisted dependencies

---

auth/app/build.gradle.kts
auth/app/src/main/java/com/google/firebase/quickstart/auth/java/GoogleSignInFragment.java
auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInFragment.kt

This PR:
- Removes Google One Tap sign-in, which is deprecated 
- Adds Credential Manager, which is the recommended way to fetch users' credentials

Add Credential Manager to Auth samples

---

build.gradle.kts
functions/app/build.gradle.kts

This should undo the changes from #2640 and #2641 now that https://github.com/firebase/firebase-android-sdk/issues/6522 has been fixed

chore: unpin functions version

---

firebase-ai/gradle/libs.versions.toml

Some of the versions were declared in the top-level `libs.versions.toml` file instead.
Also, sorted alphabetically the entries in the file.

[firebase-ai] Add missing entries to libs.versions.toml

---

firebase-ai/app/src/main/java/com/google/firebase/quickstart/ai/FirebaseAISamples.kt

https://developers.googleblog.com/en/gemini-2-5-flash-image-now-ready-for-production-with-new-aspect-ratios/

remove preview suffix for nanobanana
